dist: xenial
language: cpp

compiler:
  - gcc

before_install:
    # - sudo apt-get update
    - sudo apt-get install libopencv-dev

install:
    - mkdir build
    - cd build
    - cmake ..
    - make


script:
    - cd ../merlict
    - ../build/merlict-test
