language: cpp
compiler: gcc
dist: xenial

# C++ 17 install from:
# https://github.com/richelbilderbeek/travis_gcc_cpp17/blob/master/.travis.yml

before_install:
    # C++17
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - pip install --user cpp-coveralls

install:
    - sudo apt-get install -qq libopencv-dev
    # C++17
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
    - mkdir build
    - cd build

    - cmake -DUSE_GCOV=yes ..
    - make

    - cd ..
    - ./build/merlict-test

after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

