language: python
python:
    - 3.7
compiler: gcc
dist: xenial

# C++ 17 install from:
# https://github.com/richelbilderbeek/travis_gcc_cpp17/blob/master/.travis.yml

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda  # get latest conda version
  - conda info -a

install:
  - sudo apt-get install -qq libopencv-dev
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip numpy swig
  - source activate test

script:
  # avoid cmake & make for the momement, they slow down the test so much
  # - mkdir build
  # - cd build
  # - cmake ..
  # - make
  # - cd ..
  # - ./build/merlict-test

  # - echo "trying out one_source.py"
  - ./one_source.py
  - g++ merlict_test.cpp merlict.cpp -o merlict_test -O1
  - ./merlict_test

  - swig -c++ -python -o merlict_wrap.cpp merlict.i
  - python setup.py build_ext --inplace
  - pip install -e .
  - pytest
