language: cpp
compiler: gcc
dist: xenial

# C++ 17 install from:
# https://github.com/richelbilderbeek/travis_gcc_cpp17/blob/master/.travis.yml

before_install:
    # C++17
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libopencv-dev
    # C++17
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
    - mkdir build
    - cd build

    - echo "int main() {return 0;}" > mini_main.cpp
    - /usr/bin/g++ -o no_parameters -c mini_main.cpp
    - ./no_parameters
    - /usr/bin/g++ -std=c++17 -pthread -Wall -Wextra -pedantic -O1 -g -I -o many_parameters -c mini_main.cpp
    - ./many_parameters

    - cmake ..
    - make

    - cd ../merlict
    - ../build/merlict-test



