language: python
python:
    - 3.6
compiler: gcc
dist: xenial
addons:
  apt:
    packages: lcov

# C++ 17 install from:
# https://github.com/richelbilderbeek/travis_gcc_cpp17/blob/master/.travis.yml
before_install:
    # C++17
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libopencv-dev
    - sudo apt-get install swig
    # C++17
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

    - sudo apt-get install -qq gcc-6
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy numpy


script:
    - echo "cmake build"
    - mkdir build
    - cd build
    - cmake -DUSE_COV=yes ..
    - make
    - cd ..
    - ./build/merlict-test

    - echo "one_source.py build"
    - ./one_source.py
    - g++ merlict_test.cpp merlict.cpp -o merlict_test -O1
    - ./merlict_test

    - swig -c++ -python -o merlict_wrap.cpp merlict.i
    - python setup.py build_ext --inplace
    - pip install -e .
    - pytest -v


after_success:
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
    - lcov --list coverage.info # debug info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"






