language: cpp

compiler:
  - gcc

before_install:

    - apt-get install libopencv-dev

install:
    - mkdir build
    - cd build
    - cmake ..
    - make


script:
    - cd ../merlict
    - ../build/merlict-test
