dist: xenial
language: generic
addons:
  apt:
    packages: lcov


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda  # get latest conda version
  - conda info -a

install:
  - sudo apt-get install -qq libopencv-dev

  - conda create --yes -n test python=3.7 nomkl pip numpy swig gxx_linux-64 pytest
  - source activate test

script:
  - echo 'cmake build'
  - mkdir build
  - cd build
  - cmake -DUSE_COV=yes ..
  - make
  - cd ..
  - ./build/merlict-test

  - echo 'Test one_source build'
  - ./one_source.py
  - $GXX merlict_test.cpp merlict.cpp -o merlict_test -O1
  - ./merlict_test

  - swig -c++ -python -o merlict_wrap.cpp merlict.i
  - python setup.py build_ext --inplace
  - pip install -e .
  - pytest -v


after_success:
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
    - lcov --list coverage.info # debug info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
